---
- name: Get Date from Ansible Host
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Get Date
    ansible.builtin.command: date +%Y%m%d
    register: timestamp

- name: Backup Cisco ASA Config
  hosts: cisco_asa
  gather_facts: false
  collections:
    - cisco.asa

  tasks:

  - name: Perform Cisco ASA Backup
    cisco.asa.asa_config:
      backup: true
      backup_options:
        dir_path: /path/to/where/backups/will/be/stored/on/ansible/host
        filename: "config-{{ hostvars.localhost.timestamp.stdout }}.txt"
      passwords: true
